name: Zig Test and Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: ./.github/workflows/zig-setup.yml@main

      - name: Unit testing
        run: zig build test --summary all

      - name: Run benchmarks
        run: zig build bench -Doptimize=ReleaseFast

      - name: Run node
        run: |
          zig build -Doptimize=Debug run -- node &
          BITCOIN_NODE_PID=$!
          sleep 1
          kill $BITCOIN_NODE_PID
